version: '3.7'

services:
  mealprephelper:
    build: .
    image: mealprephelper
    env_file:
      - env/local.env
    volumes:
      - ./mealprephelper:/app/mealprephelper
    ports:
      - 5555:5555
    restart: always
    working_dir: /app
    command: uvicorn mealprephelper.main:app --reload --host 0.0.0.0 --port 5555
