"""Created tables for recipes and recipe types with initial four recipe types

Revision ID: 6977cafa0150
Revises: 
Create Date: 2020-04-19 15:06:23.805986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import insert, orm

revision = "6977cafa0150"
down_revision = None
branch_labels = None
depends_on = None


INIT_RECIPE_TYPES = [
    {"name": "breakfast", "color": "#008000"},
    {"name": "lunch", "color": "#000080"},
    {"name": "snack", "color": "#880000"},
    {"name": "dinner", "color": "#800080"},
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    recipe_types_table = op.create_table(
        "recipe_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_types_id"), "recipe_types", ["id"], unique=False)
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_id"), "recipes", ["id"], unique=False)
    op.create_table(
        "recipe_recipe_types_association_table",
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("recipe_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"],),
        sa.ForeignKeyConstraint(["recipe_type_id"], ["recipe_types.id"],),
    )

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(insert(recipe_types_table).values(INIT_RECIPE_TYPES))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_recipe_types_association_table")
    op.drop_index(op.f("ix_recipes_id"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_recipe_types_id"), table_name="recipe_types")
    op.drop_table("recipe_types")
    # ### end Alembic commands ###
