"""Created tables for recipes and recipe_types

Revision ID: 50da2b884709
Revises: 
Create Date: 2020-04-19 13:53:43.053308

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50da2b884709"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_types_id"), "recipe_types", ["id"], unique=False)
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_id"), "recipes", ["id"], unique=False)
    op.create_table(
        "recipe_recipe_types_association_table",
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("recipe_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"],),
        sa.ForeignKeyConstraint(["recipe_type_id"], ["recipe_types.id"],),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_recipe_types_association_table")
    op.drop_index(op.f("ix_recipes_id"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_recipe_types_id"), table_name="recipe_types")
    op.drop_table("recipe_types")
    # ### end Alembic commands ###
